### ISSUE TITLE
Dati referendum_iniziative_popolare non aggiornati 

### ISSUE THREAD

**Issue by vi-enne** [ondata/liberiamoli-tutti#3]
Ciao,
L'ultimo commit in `referendum_iniziative_popolare` è di 19 ore fa.
Potrebbe esserci un problema nella action?
Il sito ha anche leggermente cambiato stile.

Grazie,
Vittorio

**Comment by aborruso** [comment]
Caro @vi-enne qualche giorno fa ho modificato la frequenza di update.

Perché superate le 500.000 firme sul tema "hot", pensavo potesse essere di meno interesse. Ma è un pensiero scemo probabilmente.

Riporto a frequenza oraria?

**Comment by vi-enne** [comment]
Grazie del chiarimento!
Credo vada bene così, tanto più che dal 30 settembre (termine massimo per raccolta firme) la situazione sarà molto più calma.

Chiudo
